import type { ConfigKeyDef } from "@commerce/contracts";

/**
 * Catálogo tipado de claves de config conocidas (C1/D8). Cada clave declara su JSON
 * Schema (validación al escribir), su default de plataforma y su categoría. Las claves de
 * dinero/reglas son `sensitive` → exigen auditoría (actor + reason) y effective-dating.
 *
 * Los valores por defecto salen de los escenarios de rentabilidad de Fase 0 (L4): son
 * PARÁMETROS, no constantes del código. Cambiarlos es config, no un deploy.
 */
export const CONFIG_KEYS = {
  "commission.rateBps": {
    key: "commission.rateBps",
    jsonSchema: { type: "integer", minimum: 0, maximum: 5000 },
    defaultValue: 700, // 7% (L4)
    category: "money",
    sensitive: true,
    description: "Comisión de la plataforma sobre el GMV, en puntos básicos (700 = 7%).",
  },
  "delivery.customerChargeMinor": {
    key: "delivery.customerChargeMinor",
    jsonSchema: { type: "integer", minimum: 0 },
    defaultValue: 150000, // $1.500 (centavos)
    category: "money",
    sensitive: true,
    description: "Cargo de delivery al cliente por defecto, en centavos.",
  },
  "delivery.freeOverOrderTotalMinor": {
    key: "delivery.freeOverOrderTotalMinor",
    jsonSchema: { type: "integer", minimum: 0 },
    defaultValue: 5000000, // gratis sobre $50.000 (L4)
    category: "money",
    sensitive: true,
    description: "Umbral de compra por sobre el cual el delivery es gratis, en centavos.",
  },
  "delivery.auxilioCostMinor": {
    key: "delivery.auxilioCostMinor",
    jsonSchema: { type: "integer", minimum: 0 },
    defaultValue: 200000, // $2.000 (envío de auxilio nocturno)
    category: "money",
    sensitive: true,
    description: "Costo del Envío de Auxilio (nocturno/urgente) al cliente, en centavos.",
  },
  "features.auxilioDelivery": {
    key: "features.auxilioDelivery",
    jsonSchema: { type: "boolean" },
    defaultValue: true,
    category: "features",
    sensitive: false,
    description: "Habilita el Envío de Auxilio como método de entrega en el checkout.",
  },
  "payments.transferDiscountPercent": {
    key: "payments.transferDiscountPercent",
    jsonSchema: { type: "integer", minimum: 0, maximum: 90 },
    defaultValue: 10, // 10% off por pago con transferencia
    category: "money",
    sensitive: true,
    description: "Descuento por pago con transferencia bancaria, en porcentaje entero (10 = 10%).",
  },
  "storefront.featuredCount": {
    key: "storefront.featuredCount",
    jsonSchema: { type: "integer", minimum: 2, maximum: 12 },
    defaultValue: 4,
    category: "branding",
    sensitive: false,
    description: "Cantidad de productos destacados en la home.",
  },
  "storefront.listColumns": {
    key: "storefront.listColumns",
    jsonSchema: { type: "integer", enum: [2, 3, 4] },
    defaultValue: 3,
    category: "branding",
    sensitive: false,
    description: "Columnas de la grilla del listado de productos (2, 3 o 4).",
  },
  "storefront.promoText": {
    key: "storefront.promoText",
    jsonSchema: { type: "string", maxLength: 160 },
    defaultValue: "Envíos gratis en Gualeguay en compras superiores a $25.000",
    category: "text",
    sensitive: false,
    description: "Texto de la barra promocional (arriba de todo).",
  },
  "storefront.heroTitle": {
    key: "storefront.heroTitle",
    jsonSchema: { type: "string", maxLength: 120 },
    defaultValue: "Todo lo que tu mascota necesita,",
    category: "text",
    sensitive: false,
    description: "Título del hero de la home (primera parte, en negro).",
  },
  "storefront.heroHighlight": {
    key: "storefront.heroHighlight",
    jsonSchema: { type: "string", maxLength: 60 },
    defaultValue: "sin salir de casa",
    category: "text",
    sensitive: false,
    description: "Tramo destacado del título del hero (en color de marca).",
  },
  "storefront.heroSubtitle": {
    key: "storefront.heroSubtitle",
    jsonSchema: { type: "string", maxLength: 220 },
    defaultValue: "Alimentos, accesorios, higiene y más. Envíos rápidos en Gualeguay, Entre Ríos.",
    category: "text",
    sensitive: false,
    description: "Subtítulo del hero de la home.",
  },
  "storefront.footerBlurb": {
    key: "storefront.footerBlurb",
    jsonSchema: { type: "string", maxLength: 320 },
    defaultValue: "Tu tienda de mascotas en Gualeguay, Entre Ríos. Alimentos, accesorios e higiene con envío en el día y atención por WhatsApp.",
    category: "text",
    sensitive: false,
    description: "Texto descriptivo del footer.",
  },
  "storefront.heroImageUrl": {
    key: "storefront.heroImageUrl",
    jsonSchema: { type: "string", maxLength: 500 },
    defaultValue: "",
    category: "branding",
    sensitive: false,
    description: "URL de la imagen principal del hero de la home (aprox. 1080×450). Vacío = placeholder.",
  },
  "storefront.adoptionsBannerImageUrl": {
    key: "storefront.adoptionsBannerImageUrl",
    jsonSchema: { type: "string", maxLength: 500 },
    defaultValue: "",
    category: "branding",
    sensitive: false,
    description: "URL de la imagen del banner de Adopciones en la home. Vacío = placeholder.",
  },
  "storefront.perks": {
    key: "storefront.perks",
    jsonSchema: {
      type: "array",
      maxItems: 6,
      items: { type: "object", required: ["t", "s"], properties: { t: { type: "string" }, s: { type: "string" } }, additionalProperties: false },
    },
    defaultValue: [
      { t: "Envíos en el mismo día", s: "Pedidos antes de las 18 hs" },
      { t: "Envío de Auxilio", s: "Nocturno y feriados" },
      { t: "Compra 100% segura", s: "Transferencia o Mercado Pago" },
    ],
    category: "text",
    sensitive: false,
    description: "Beneficios cortos bajo el hero (título + subtítulo cada uno).",
  },
  "storefront.benefits": {
    key: "storefront.benefits",
    jsonSchema: {
      type: "array",
      maxItems: 8,
      items: { type: "object", required: ["t", "s"], properties: { t: { type: "string" }, s: { type: "string" } }, additionalProperties: false },
    },
    defaultValue: [
      { t: "ENVÍO DE AUXILIO", s: "Emergencias 20:00–23:00, feriados 10:00–22:00" },
      { t: "Bolsas cerradas", s: "10 / 15 kg — las mejores marcas" },
      { t: "Fraccionado por kilo", s: "1,5 / 3 / 5 kg" },
      { t: "Ofertas todas las semanas", s: "Precios especiales" },
      { t: "Atención personalizada", s: "Te asesoramos por WhatsApp" },
    ],
    category: "text",
    sensitive: false,
    description: "Franja de beneficios de la home (título + subtítulo cada uno).",
  },
  "delivery.cadeteCostMinor": {
    key: "delivery.cadeteCostMinor",
    jsonSchema: { type: "integer", minimum: 0 },
    defaultValue: 250000, // $2.500 (costo real de una entrega, L4)
    category: "money",
    sensitive: true,
    description: "Costo real de una entrega (lo que cobra el cadete), en centavos.",
  },
  "delivery.subsidySource": {
    key: "delivery.subsidySource",
    jsonSchema: { type: "string", enum: ["platform", "merchant", "promo", "none"] },
    defaultValue: "platform",
    category: "rules",
    sensitive: true,
    description: "Quién financia el gap entre el costo del cadete y lo que paga el cliente.",
  },
  "orders.maxSellersPerOrder": {
    key: "orders.maxSellersPerOrder",
    jsonSchema: { type: "integer", minimum: 1, maximum: 100 },
    defaultValue: 1, // V1: 1 pedido = 1 comercio (config, NO código — [E1])
    category: "features",
    sensitive: false,
    description: "Máximo de comercios por pedido. V1 = 1; subirlo habilita multi-seller.",
  },
  "features.customerAgent": {
    key: "features.customerAgent",
    jsonSchema: { type: "boolean" },
    defaultValue: true,
    category: "features",
    sensitive: false,
    description: "Habilita el Customer Shopping Agent.",
  },
  "features.adoptions": {
    key: "features.adoptions",
    jsonSchema: { type: "boolean" },
    defaultValue: true,
    category: "features",
    sensitive: false,
    description: "Habilita la sección de Adopciones / callejeritos en la tienda.",
  },
  "storefront.adoptionsTitle": {
    key: "storefront.adoptionsTitle",
    jsonSchema: { type: "string", maxLength: 60 },
    defaultValue: "Adopciones",
    category: "text",
    sensitive: false,
    description: "Nombre de la sección de adopciones (nav y título).",
  },
  "features.foodCalculator": {
    key: "features.foodCalculator",
    jsonSchema: { type: "boolean" },
    defaultValue: true,
    category: "features",
    sensitive: false,
    description: "Habilita la calculadora de consumo de alimento y perfiles de mascota.",
  },
  "features.foodComparator": {
    key: "features.foodComparator",
    jsonSchema: { type: "boolean" },
    defaultValue: true,
    category: "features",
    sensitive: false,
    description: "Habilita el comparador de alimentos (costo por día / conveniencia).",
  },
  "features.quickReorder": {
    key: "features.quickReorder",
    jsonSchema: { type: "boolean" },
    defaultValue: true,
    category: "features",
    sensitive: false,
    description: "Habilita la compra rápida: 'Repetir última compra' en 1 clic para clientes reconocidos.",
  },
  "nutrition.factors": {
    key: "nutrition.factors",
    jsonSchema: {
      type: "object",
      additionalProperties: { type: "number", minimum: 0.5, maximum: 4 },
    },
    defaultValue: { cachorro: 2.0, adulto_bajo: 1.2, adulto_normal: 1.4, adulto_activo: 1.6, senior: 1.2 },
    category: "rules",
    sensitive: false,
    description: "Factores de mantenimiento (× RER) por etapa/actividad para la calculadora de consumo.",
  },
  "features.loyalty": {
    key: "features.loyalty",
    jsonSchema: { type: "boolean" },
    defaultValue: false,
    category: "features",
    sensitive: false,
    description: "Habilita el módulo de fidelización.",
  },
  "branding.primaryColor": {
    key: "branding.primaryColor",
    jsonSchema: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    defaultValue: "#2563eb",
    category: "branding",
    sensitive: false,
    description: "Color primario de marca del tenant.",
  },
  "branding.displayName": {
    key: "branding.displayName",
    jsonSchema: { type: "string", minLength: 1, maxLength: 80 },
    defaultValue: "Commerce",
    category: "branding",
    sensitive: false,
    description: "Nombre visible de la marca del tenant.",
  },
  "branding.secondaryColor": {
    key: "branding.secondaryColor",
    jsonSchema: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    defaultValue: "#1e293b",
    category: "branding",
    sensitive: false,
    description: "Color secundario/acento de marca del tenant.",
  },
  "branding.logoUrl": {
    key: "branding.logoUrl",
    jsonSchema: { type: "string", maxLength: 600 },
    defaultValue: "",
    category: "branding",
    sensitive: false,
    description: "URL del logo del tenant (http/https). Vacío = sin logo.",
  },
  "branding.bannerText": {
    key: "branding.bannerText",
    jsonSchema: { type: "string", maxLength: 160 },
    defaultValue: "",
    category: "branding",
    sensitive: false,
    description: "Texto/lema del banner de la tienda. Vacío = sin banner de texto.",
  },
  "branding.bannerImageUrl": {
    key: "branding.bannerImageUrl",
    jsonSchema: { type: "string", maxLength: 600 },
    defaultValue: "",
    category: "branding",
    sensitive: false,
    description: "URL de imagen de fondo del banner (http/https). Vacío = fondo de color.",
  },
  "branding.layout": {
    key: "branding.layout",
    jsonSchema: { type: "string", enum: ["grid", "list"] },
    defaultValue: "grid",
    category: "branding",
    sensitive: false,
    description: "Disposición del catálogo en la tienda: grilla o lista.",
  },
  "branding.font": {
    key: "branding.font",
    jsonSchema: { type: "string", enum: ["system", "serif", "rounded", "mono"] },
    defaultValue: "system",
    category: "branding",
    sensitive: false,
    description: "Familia tipográfica de la tienda (system/serif/rounded/mono).",
  },
  "branding.buttonShape": {
    key: "branding.buttonShape",
    jsonSchema: { type: "string", enum: ["rounded", "pill", "square"] },
    defaultValue: "rounded",
    category: "branding",
    sensitive: false,
    description: "Forma de los botones de la tienda (rounded/pill/square).",
  },
  "contact.whatsapp": {
    key: "contact.whatsapp",
    jsonSchema: { type: "string", maxLength: 20, pattern: "^[0-9]{0,20}$" },
    defaultValue: "",
    category: "contact",
    sensitive: false,
    description: "Número de WhatsApp del comercio (solo dígitos, con código de país; ej: 5493444123456). Vacío = sin WhatsApp.",
  },
  "contact.whatsappMessage": {
    key: "contact.whatsappMessage",
    jsonSchema: { type: "string", maxLength: 160 },
    defaultValue: "¡Hola! Quiero hacer un pedido.",
    category: "contact",
    sensitive: false,
    description: "Mensaje prellenado al abrir WhatsApp desde la tienda.",
  },
  "ops.deliveryPin": {
    key: "ops.deliveryPin",
    jsonSchema: { type: "string", maxLength: 32 },
    defaultValue: "",
    category: "ops",
    sensitive: true,
    description: "PIN de acceso a la pantalla de reparto (lo usa el repartidor en vez del token de admin). Vacío = solo el token de admin abre reparto.",
  },
  "tenant.vertical": {
    key: "tenant.vertical",
    jsonSchema: { type: "string", minLength: 1 },
    defaultValue: "generic",
    category: "features",
    sensitive: false,
    description: "Vertical activo del tenant (pet_shop, etc.). Define qué módulo de vertical aplica.",
  },
  "modules.enabled": {
    key: "modules.enabled",
    jsonSchema: { type: "array", items: { type: "string" } },
    defaultValue: [],
    category: "features",
    sensitive: false,
    description: "Módulos habilitados para el tenant (feature flags de módulo).",
  },
} as const satisfies Record<string, ConfigKeyDef>;

export type ConfigKeyName = keyof typeof CONFIG_KEYS;

export function getConfigKeyDef(key: string): ConfigKeyDef | undefined {
  return (CONFIG_KEYS as Record<string, ConfigKeyDef>)[key];
}
